name: Build and Publish Docker Image
env:
  DOCKER_HUB_ACCOUNT: trentrosenbaum
  APP_NAME: example-go-github-actions
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  build-and-publish:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ DOCKER_HUB_ACCOUNT }}/${{ APP_NAME }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}